name: visual-ci-workflow

on: 
  push:
    branches:
    - 'main'
    
env:
  URL: "${{ secrets.URL }}"
  USERNAME: "${{ secrets.USERNAME }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  BADUSERNAME: "${{ secrets.USERNAME }}"
  BADPASSWORD: "${{ secrets.BADPASSWORD }}"
  FIRSTNAME: "${{ secrets.FIRSTNAME }}"
  LASTNAME: "${{ secrets.LASTNAME }}"
  ZIPCODE: "${{ secrets.ZIPCODE }}"
  

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - run: npm install
    - run: npm run test
    - run: npm run lint
    

  API-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - run: npm run test-backend
    - run: npm run lint
    


  
 
